### ISSUE TITLE
[zh-cn]The code implementation does not match the conclusion.

### ISSUE THREAD

**Issue by HUNTER-THE-ONE** [mdn/translated-content#18198]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Styling_text/Styling_links

### 与此议题相关的小节或标题？

样式化链接

### 哪些信息是错误、无用或不完善的？

<ul>
  <li><a href="#">Home</a></li>
  <li><a href="#">Pizza</a></li>
  <li><a href="#">Music</a></li>
  <li><a href="#">Wombats</a></li>
  <li><a href="#">Finland</a></li>
</ul>

### 你期望看到什么？

<ul>
  <li><a href="#">Home</a></li><li><a href="#">Pizza</a></li><li><a href="#">Music</a></li><li><a href="#">Wombats</a></li><li><a href="#">Finland</a></li>
</ul>

### 你有什么支持的链接、参考或引用？

```html
<ul>
  <li><a href="#">Home</a></li>
  <li><a href="#">Pizza</a></li>
  <li><a href="#">Music</a></li>
  <li><a href="#">Wombats</a></li>
  <li><a href="#">Finland</a></li>
</ul>

```

```css
body,
html {
  margin: 0;
  font-family: sans-serif;
}

ul {
  padding: 0;
  width: 100%;
}

li {
  display: inline;
}

a {
  outline: none;
  text-decoration: none;
  display: inline-block;
  width: 19.5%;
  margin-right: 0.625%;
  text-align: center;
  line-height: 3;
  color: black;
}

li:last-child a {
  margin-right: 0;
}

a:link,
a:visited,
a:focus {
  background: yellow;
}

a:hover {
  background: orange;
}

a:active {
  background: red;
  color: white;
}

```

### 你还想补充什么内容？

<li>元素之间的换行在显示时是存在部分空间的，导致溢出ul。删掉后即可，或者使用更新的en-US版本的讲义。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/css/styling_text/styling_links`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Styling_text/Styling_links
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/css/styling_text/styling_links/index.md
* Last commit: https://github.com/mdn/translated-content/commit/bff0d2bf12b7cafc4d2bfb9eb0b759419f660324
* Document last modified: 2023-11-30T01:14:28.000Z

</details>
