### ISSUE TITLE
「2行だから :nth-of-type(2) 」は、表記揺れかつ、対処療法的で非論理的。残念な対応。

### ISSUE THREAD

**Issue by MaruniUmebachi** [mdn/translated-content#26907]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/HTML/Reference/Elements/table

### この問題に関する節や見出しはどこですか。

高度な表のスタイル設定

### 不完全、不親切、不完全であった情報は何ですか。

```css
thead > tr:nth-of-ype(2) {
  border-bottom: 2px solid rgb(140 140 140);
}
```

### どう表示されるべきだと思いますか。

```css
thead > tr:last-of-type {
  border-bottom: 2px solid rgb(140 140 140);
}
```

### 他に共有したいことはありますか。

```css
table {
  border-collapse: collapse;
  border-spacing: 0;
  border: 2px solid rgb(140 140 140);
  font:
    16px "Open Sans",
    Helvetica,
    Arial,
    sans-serif;
}

caption {
  caption-side: bottom;
  padding: 10px;
  font-weight: bold;
}

th,
td {
  border: 1px solid rgb(160 160 160);
  padding: 4px 6px;
}

th {
  vertical-align: bottom;
}

thead > tr {
  background-color: rgb(228 240 245);
}

/* そもそも、文書内で表記揺れを起こしている */
thead > tr:nth-of-type(2) {
  border-bottom: 2px solid rgb(140 140 140);
}

/* ここの表記と揺れている */
thead > tr:last-of-type > th:nth-of-type(1) {
  background-color: rgb(225 255 225);
}

thead > tr:last-of-type > th:nth-of-type(2) {
  background-color: rgb(255 225 225);
}

tbody > tr > th:first-of-type {
  text-align: left;
  background-color: rgb(225 229 244);
}

tbody > tr:nth-of-type(even) {
  background-color: rgb(237 238 242);
}

tbody > tr > td:last-of-type {
  text-align: right;
}

tfoot > tr {
  border-top: 2px dashed rgb(140 140 140);
  background-color: rgb(228 240 245);
}

tfoot th,
tfoot td {
  text-align: right;
  font-weight: bold;
}
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/html/reference/elements/table`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/HTML/Reference/Elements/table
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/html/reference/elements/table/index.md
* Last commit: https://github.com/mdn/translated-content/commit/6a64233df37ce128497c0590ff6c14e6ff096d8e
* Document last modified: 2025-04-19T07:28:06.000Z

</details>
