### ISSUE TITLE
Issue with "Flexbox": inaccurate CSS code example

### ISSUE THREAD

**Issue by Uneld** [mdn/translated-content#6239]
MDN URL: https://developer.mozilla.org/ru/docs/Learn/CSS/CSS_layout/Flexbox

#### What information was incorrect, unhelpful, or incomplete?

[Наконец, мы устанавливаем размер кнопке, мы даём ему значение `flex 1`.](https://github.com/mdn/translated-content/blob/main/files/ru/learn/css/css_layout/flexbox/index.html?plain=1#L293-L298)

```css
button {
    flex: 1;
    margin: 5px;
    font-size: 18px;
    line-height: 1.5;
}
```

#### Specific section or headline?

[Вложенные flex блоки](https://developer.mozilla.org/ru/docs/Learn/CSS/CSS_layout/Flexbox#%D0%B2%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5_flex_%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8)

#### What did you expect to see?
Наконец, мы устанавливаем размер кнопке, мы даём ему значение `flex: 1 auto`. 

```css
button {
    flex: 1 auto;
    margin: 5px;
    font-size: 18px;
    line-height: 1.5;
}
```

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `ru/learn/css/css_layout/flexbox`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/CSS/CSS_layout/Flexbox
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/css/css_layout/flexbox/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d5dfc54d019d9bf8f58eeac16e41c2b97496eac9
* Document last modified: 2021-12-17T01:16:30.000Z

</details>
